POST http://localhost:9000/login
Content-Type: application/json

	{  
	"password": "12345678", 
	"email": "test@test.com"
    

	}

###
GET http://localhost:9000/users/619054d2c33a59fa7a362022




###
POST http://localhost:9000/register
Content-Type: application/json

{
"firstName": "Martina",
"lastName": "Engels",
"email": "engels@gazaphili.com",
"password": "123",
"avatar": "😥",
"dateOfBirth": 13122000,
"address": {
		"city": "Azi",
		"street": "Main Street 45",
		"zip": "15011",
		"country": "Germany"
	},
	"phoneNumber": "0124567844",
	"blogPosts": {

		"title": "Fangs in the skies",
		"body":"Circling the deaf zones of human accoustic competence. Also, in some situations I do need to get the password field, like when the user wants to login or change the password. Also, in some situations I do need to get the password field, like when the user wants to login or change the password."
	} 

"blogPosts":[    ]

}


