
###
GET http://localhost:9000/getPost

###
GET http://localhost:9000/posts/getPost


###

PUT http://localhost:9000/posts/writePost
Content-Type: application/json
	
	{	
		
		
		"email":"zhonglei@gmail.com",
		"title": "The rustle in the mount Part III",
		"content": "They took my scarf and my staff. They robbed me of my dignity and thought that would emasciate my humanity. But I rose up like the proverbial phoneix, and like a lark sang to the heavens the perreniality of my humanity. The data showed the epidemic gaining pace with 131,731 cases detected over past seven days, compared to 73,200 cases reported for all of October.",
		"author": "Zhang Licun"
		
				
	}


###
POST http://localhost:9000/users/login
Content-Type: application/json

	{  
	"password": "12345678", 
	"email": "zhonglei@gmail.com"
    

	}

###
GET http://localhost:9000/users/users/61a0a72010d9efe46b27591e



###
POST http://localhost:9000/users/register
Content-Type: application/json

{
"firstName": "Zonglei",
"lastName": "Liu",
"email": "zhonglei@gmail.com",
"password": "12345678",
"avatar": "{image: src='http://placekitten.com/g/150/150'}",
"dateOfBirth": 13122000,
"address": {
		"city": "Azi",
		"street": "Main Street 45",
		"zip": "15011",
		"country": "Germany"
	},
	"phoneNumber": "0124567844",
	"posts" :{	
		
		"author": "Zhang Licun",
		"email": "licunana@gazaphili.com",
		"title": "The Day the World Got Duped",
		"content": "BRUSSELS (Reuters) - The European Commission on Thursday proposed that from Jan. 10 next year the European Union's COVID-19 vaccination certificates be valid for nine months after full vaccination, and also opened the way for boosters to be linked to such passes."
		
				
	}



}


