
###
GET http://localhost:9000/getPosts 

###

PUT http://localhost:9000/article
Content-Type: application/json
	
	{	
		
		
		"email": "gentlesoul@gazaphili.com",
		"title": "Worm birds raising storms",
		"content": "PRAGUE (Reuters) -The Czech Republic reported 27,717 new coronavirus cases for Thursday, the highest daily tally in the country of 10.7 million since the pandemic started, Health Ministry data showed on Friday. The data showed the epidemic gaining pace with 131,731 cases detected over past seven days, compared to 73,200 cases reported for all of October.",
		"author": "Zhang Licun"
		
				
	}


###
POST http://localhost:9000/login
Content-Type: application/json

	{  
	"password": "12345678", 
	"email": "gentlesoul@gazaphili.com"
    

	}

###
GET http://localhost:9000/users/61a0a72010d9efe46b27591e



###
POST http://localhost:9000/register
Content-Type: application/json

{
"firstName": "Zonglei",
"lastName": "Liu",
"email": "zhonglei@gmail.com",
"password": "12345678",
"avatar": "{image: src='http://placekitten.com/g/150/150'}",
"dateOfBirth": 13122000,
"address": {
		"city": "Azi",
		"street": "Main Street 45",
		"zip": "15011",
		"country": "Germany"
	},
	"phoneNumber": "0124567844",
	"posts" :{	
		
		"author": "Zhang Licun",
		"email": "licunana@gazaphili.com",
		"title": "The Day the World Got Duped",
		"content": "BRUSSELS (Reuters) - The European Commission on Thursday proposed that from Jan. 10 next year the European Union's COVID-19 vaccination certificates be valid for nine months after full vaccination, and also opened the way for boosters to be linked to such passes."
		
				
	}



}


